### ISSUE TITLE
get_market_cap doesn't work anymore?

### ISSUE THREAD

**Issue by weiyiw0816** [AndrewRPorter/nasdaq-stock-quote#1]
it seems get_market_cap doesn't work anymore. Can you check?

**Comment by AndrewRPorter** [comment]
It does seem to be broken, let me look more into this. NASDAQ changed that way their HTML is formatted so a few of the methods are broken such as get_market_cap(), get_year_low() and get_year_high()

**Comment by AndrewRPorter** [comment]
This has been fixed with 0706d967724b59f724ce908a2353edbdfd5a0cad
